### ISSUE TITLE
Release CRAN versions

### ISSUE THREAD

**Issue by maelle** [vpnagraj/hei#13]
I've just noted that there is no release in the Github repo although the package is on CRAN. In the future, for archiving you might consider releasing each CRAN version and linking it to NEWS.md.

This issue is part of a [JOSS review](https://github.com/openjournals/joss-reviews/issues/417).

**Comment by vpnagraj** [comment]
thanks @maelle ... now linking to CRAN version 0.1.0 of the package in the NEWS.md file ea5ff7c
