### ISSUE TITLE
Functional claim

### ISSUE THREAD

**Issue by maelle** [vpnagraj/hei#14]
I see the test "HEI score is same as original validation data" which is great. I even think it should be mentioned explicitely in paper.md (i.e. that it has been validated that the R code produces the same output as the SAS original script).

This issue is part of a [JOSS review](https://github.com/openjournals/joss-reviews/issues/417).

**Comment by vpnagraj** [comment]
@maelle that's a good point ... i've included as part of the paper revisions in 4769b93
