### ISSUE TITLE
Create a pkgdown website?

### ISSUE THREAD

**Issue by maelle** [vpnagraj/hei#16]
Since you have written two useful vignettes, why not create a [`pkgdown`](https://github.com/hadley/pkgdown) website to make the whole documentation more easily browsable? This is obviously only a suggestion (like many of the issues I've opened, I'll make a summary) but I've had an excellent experience with `pkgdown`. If you do create one, add its URL to the Github repository URL field.

This issue is part of a [JOSS review](https://github.com/openjournals/joss-reviews/issues/417).

**Comment by maelle** [comment]
Added benefit if you create a `pkgdown` website, when writing "An example of how to do this is provided in a second vignette." in the first vignette you could have a direct link to that second vignette.

**Comment by vpnagraj** [comment]
@maelle a `pkgdown` site would be awesome ... i'll add it as an enhancement for our project

**Comment by maelle** [comment]
And it actually demands very little work :-)

**Comment by vpnagraj** [comment]
@maelle we just set up the pkgdown site:

<https://timfolsom.github.io/hei/>

all it took was:

```
devtools::install_github("hadley/pkgdown")
pkgdown::build_site()
```
very very easy :)

**Comment by maelle** [comment]
Nice! See, pkgdown is awesome 😀
