### ISSUE TITLE
Make "must use valid year choice" user-friendlier

### ISSUE THREAD

**Issue by maelle** [vpnagraj/hei#22]
In the functions where the error message "must use valid year choice" can appear, it might be user-friendlier to replace it with "must use valid year choice, see the function documentation to know which ones are valid".

This issue is part of a [JOSS review](https://github.com/openjournals/joss-reviews/issues/417).

**Comment by vpnagraj** [comment]
thanks @maelle that's a really good point!

including more informative error handling via 702871c
